---
name: ðŸ†š Get godot version

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      version:
        description: "Which version we should use based on target branch"
        value: ${{ jobs.version.outputs.version }}

jobs:
  version:
    name: Get godot version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: ðŸ· Get and set godot version
        id: version
        run: |
          VERSION="${{ github.event.pull_request.base.ref || github.base_ref || github.event.release.target_commitish }}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: ðŸŒ³ Log Valid Version
        env:
          VERSION: ${{ steps.version.outputs.version }}
        run: echo "$VERSION"

