---
name: ðŸ†š Get godot version

on:
  workflow_call:
    outputs:
      version:
        description: "Which version we should use based on target branch"
        value: ${{ jobs.version.outputs.version }}

# We use a godot tag(rc version) as default version for master
# because the api is changing often and this would lead to a lot of struggle
env:
  MASTER_VERSION: 4.1

jobs:
  version:
    name: Get godot version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: ðŸ· Get and set godot version
        id: version
        run: |
          VERSION="${{ github.event.pull_request.base.ref || github.base_ref || github.event.release.target_commitish }}"
          if [[ $VERSION == "master" ]]; then
            VERSION="$MASTER_VERSION"
            echo "We are overwrite master to latest rc version: $VERSION"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: ðŸŒ³ Log Valid Version
        env:
          VERSION: ${{ steps.version.outputs.version }}
        run: echo "$VERSION"
