name: üçè iOS Builds
'on':
- push
- pull_request
env:
  GODOT_BASE_BRANCH: "4.0"
  SCONSFLAGS: '  verbose=yes   debug_symbols=no'
concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-ios
  cancel-in-progress: true
jobs:
  ios-template:
    runs-on: macos-latest
    name: Template (target=release, tools=no)
    steps:
    - name: Checkout Godot
      uses: actions/checkout@v2
      with:
        repository: godotengine/godot
        ref: ${{ env.GODOT_BASE_BRANCH }}
    - name: Checkout ECMAScript
      uses: actions/checkout@v2
      with:
        path: ${{github.workspace}}/modules/ECMAScript/
    - name: Setup Godot build cache
      uses: ./.github/actions/godot-cache
      continue-on-error: true
    - name: Setup python and scons
      uses: ./modules/ECMAScript/.github/actions/godot-deps
      with:
        shell: sh
    - name: Compilation (armv7)
      uses: ./modules/ECMAScript/.github/actions/godot-build
      with:
        sconsflags: ${{ env.SCONSFLAGS }}
        platform: iphone
        target: release
        tools: false
        shell: sh
    - name: Upload artifact
      uses: ./.github/actions/upload-artifact
