name: üçé macOS Builds
'on':
- push
- pull_request
env:
  GODOT_BASE_BRANCH: "4.0.3-stable"
  SCONSFLAGS: verbose=yes warnings=extra module_text_server_fb_enabled=yes
concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-macos
  cancel-in-progress: true
jobs:
  build-macos:
    runs-on: macos-latest
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: Editor (target=editor, tools=yes)
          cache-name: macos-editor
          target: editor
          tools: true
          tests: false
          bin: ./bin/godot.osx.opt.tools.64
        - name: Template (target=release, tools=no)
          cache-name: macos-template
          target: template_release
          tests: false
          sconsflags: debug_symbols=no
          tools: false
    steps:
    - name: Checkout Godot
      uses: actions/checkout@v2
      with:
        repository: godotengine/godot
        ref: ${{ env.GODOT_BASE_BRANCH }}
    - name: Checkout ECMAScript
      uses: actions/checkout@v2
      with:
        path: ${{github.workspace}}/modules/javascript/
    - name: Setup Godot build cache
      uses: ./.github/actions/godot-cache
      with:
        cache-name: ${{ matrix.cache-name }}
      continue-on-error: true
    - name: Setup python and scons
      uses: ./modules/javascript/.github/actions/godot-deps
      with:
        shell: sh
    - name: Setup Vulkan SDK
      run: |
        sh misc/scripts/install_vulkan_sdk_macos.sh
    - name: Compilation
      uses: ./modules/javascript/.github/actions/godot-build
      with:
        sconsflags: ${{ env.SCONSFLAGS }}
        platform: macos
        target: ${{ matrix.target }}
        tests: ${{ matrix.tests }}
        tools: ${{ matrix.tools }}
        shell: sh

    # Execute unit tests for the editor
    - name: Unit tests
      if: ${{ matrix.tests }}
      run: |
        ${{ matrix.bin }} --version
        ${{ matrix.bin }} --help
        ${{ matrix.bin }} --test

    - name: Prepare artifact
      run: |
        strip bin/godot.*
        chmod +x bin/godot.*

    - name: Upload artifact
      uses: ./.github/actions/upload-artifact
      with:
        name: ${{ matrix.cache-name }}
