name: ğŸš¢ Publish release
'on':
  workflow_run:
    workflows:
    - ğŸ¤– Android Builds
    - ğŸ iOS Builds
    - ğŸŒ JavaScript Builds
    - ğŸ§ Linux Builds
    - ğŸ macOS Builds
    - â˜ Server Builds
    - ğŸ Windows Builds
    types:
    - completed
jobs:
  collect-template:
    runs-on: ubuntu-latest
    steps:
    - name: wait 10 min
      run: sleep 900
    - name: download artifacts
      uses: actions/download-artifact@v3
    - name: show dir
      run: ls -R && echo bob && ls */
