name: ğŸ”— GHA

# Only run pipeline on open pull_requests and master + versions + releases, we don't need it on every push
on:
  pull_request:
  push:
    branches:
      - "master"
      - "3.4"
      - "4.1"
  release:
    types: [published]

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-runner
  cancel-in-progress: true

jobs:
  get-version:
    name: ğŸ†š Get godot version
    uses: ./.github/workflows/get_version.yml

  static-checks:
    name: ğŸ“Š Static checks
    uses: ./.github/workflows/static_checks.yml
    needs: get-version
    with:
      version: ${{ needs.get-version.outputs.version }}

  android-build:
    name: ğŸ¤– Android
    needs: [static-checks, get-version]
    uses: ./.github/workflows/android_builds.yml
    with:
      version: ${{ needs.get-version.outputs.version }}

  ios-build:
    name: ğŸ iOS
    needs: [static-checks, get-version]
    uses: ./.github/workflows/ios_builds.yml
    with:
      version: ${{ needs.get-version.outputs.version }}

  linux-build:
    name: ğŸ§ Linux
    needs: [static-checks, get-version]
    uses: ./.github/workflows/linux_builds.yml
    with:
      version: ${{ needs.get-version.outputs.version }}

  macos-build:
    name: ğŸ macOS
    needs: [static-checks, get-version]
    uses: ./.github/workflows/macos_builds.yml
    with:
      version: ${{ needs.get-version.outputs.version }}

  windows-build:
    name: ğŸ Windows
    needs: [static-checks, get-version]
    uses: ./.github/workflows/windows_builds.yml
    with:
      version: ${{ needs.get-version.outputs.version }}

  web-build:
    name: ğŸŒ Web
    needs: [static-checks, get-version]
    uses: ./.github/workflows/web_builds.yml
    with:
      version: ${{ needs.get-version.outputs.version }}

  checks-done:
    if: ${{ always() }}
    name: âœ… Check builds
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ‰ Checks done
        run: |
          resultWebBuild="${{ needs.web-build.result }}"
          resultWindowsBuild="${{ needs.windows-build.result }}"          
          resultMacosBuild="${{ needs.macos-build.result }}"
          resultLinuxBuild="${{ needs.linux-build.result }}"
          resultIosBuild="${{ needs.ios-build.result }}"
          resultAndroidBuild="${{ needs.android-build.result }}"
          if [[ 
            $resultWebBuild == "success" && 
            $resultWindowsBuild == "success" && 
            $resultMacosBuild == "success" && 
            $resultLinuxBuild == "success" && 
            $resultIosBuild == "success" && 
            $resultAndroidBuild == "success" 
          ]]; 
          then
            echo "ğŸ‰ All builds were successful."
            exit 0
          else
            echo "ğŸ˜¥ Some builds were failing."
            exit 1
          fi
    needs:
      [
        web-build,
        windows-build,
        macos-build,
        linux-build,
        ios-build,
        android-build
      ]

  release:
    name: ğŸ¦… Release
    if: github.event_name == 'release' && github.event.action == 'published'
    needs: [checks-done]
    uses: ./.github/workflows/release_builds.yml
    secrets: inherit
    with:
      version: ${{ needs.get-version.outputs.version }}
